- name: Create cron jobs from host data
  ansible.builtin.cron:
    name: "{{ cron_name }}"
    user: "{{ cron_user }}"
    minute: "{{ cron_minute }}"
    hour: "{{ cron_hour }}"
    job: "{{ cron_job }}"
    state: present
  #become: true
 # become_user: "{{ cron_user }}"
  
- name: Create and adding to '{{ crontab_state_file }}'
  lineinfile:
    path: "{{ crontab_state_file }}"
    line: "{{cron_user}}:{{ cron_key }}:{{ cron_name }}:{{ cron_hour }}:{{ cron_minute }}:{{ cron_job }}"
    regexp: '^{{cron_user}}:{{ cron_key }}:'
    create: yes
