- name: Restart rhsmcertd service
  service:
    name: rhsmcertd
    state: restarted
    
- name: Reload udev rules
  systemd:
    name: systemd-udevd
    state: restarted

- name: Restart network service
  service:
    name: network
    state: restarted