---
- name: Install epel release for version '{{ ansible_distribution_major_version }}'
  command: dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm -y

- name: Install additional packages
  ansible.builtin.package:
    name:
      - epel-release
      - s3fs-fuse
    state: present
    disable_gpg_check: yes

- name: Add s3fs credentials
  lineinfile:
    path: /etc/passwd-s3fs
    line: "{{access_keys_id}}:{{secret_access_key}}"
    create: True
    mode: 0640

- name: Process s3fs mounts
  include_tasks: mount.yml
  loop: "{{s3fs_mounts | dict2items}}"
  loop_control:
    label: "{{ item.value.bucket }} -> {{ item.key }}"

- name: Command to show filesystems
  command: df -h
  register: dfminh
- name: Diplay debug message with filesystems
  debug:
    var: dfminh.stdout