- name: "Set timezone"
  community.general.timezone:
    name: "{{ timezone | default('UTC') }}"
  tags: timezone

- name: Set hostname
  ansible.builtin.include_tasks: os-set-hostname.yml

- name: Set /etc/resolve.conf
  ansible.builtin.include_tasks: os-resolve-conf.yml
  when: 
    - resolve_nameserver is defined
    - resolve_search is defined
    
- ansible.builtin.include_tasks: rhel-subscriptions.yml
  when: os_license == 'byol'

- ansible.builtin.debug:
    msg: "{{ansible_distribution}} en {{ansible_distribution_major_version}}"
