- name: "Set timezone"
  community.general.timezone:
    name: "{{ timezone | default('UTC') }}"
  tags: timezone

# - name: Set disknames
#   ansible.builtin.include_tasks: os-set-disknames.yml

# - name: Set hostname
#   ansible.builtin.include_tasks: os-set-hostname.yml

- ansible.builtin.include_tasks: rhel-subscriptions.yml
  when: os_license == 'byol'

- ansible.builtin.debug:
    msg: "{{ansible_distribution}} en {{ansible_distribution_major_version}}"
