---
- name: Check if LV exists
  command: lvdisplay /dev/{{ mount.value.vg_name }}/{{ mount.value.lv_name }}
  register: lv_check
  ignore_errors: yes

- name: Create LV if not exists
  ansible.builtin.lvol:
    vg: "{{ mount.value.vg_name }}"
    lv: "{{ mount.value.lv_name }}"
    size: "{{ mount.value.size  ~ size_postfix }}"
  when: lv_check.rc != 0

- name: Resize logical volumes
  ansible.builtin.lvol:
    vg: "{{ mount.value.vg_name }}"
    lv: "{{ mount.value.lv_name }}"
    size: "{{ mount.value.size ~ size_postfix }}"
    resizefs: yes
  when: lv_check.rc == 0 and fstype != "swap"

- name: Get filesystem type of existing LV
  command: blkid -o value -s TYPE /dev/{{ mount.value.vg_name }}/{{ mount.value.lv_name }}
  register: fs_type
  ignore_errors: yes
- name: Create filesystem on LV if it is not swap
  filesystem:
    fstype: "{{ fstype }}"
    dev: /dev/{{ mount.value.vg_name }}/{{ mount.value.lv_name }}
  when: fs_type.stdout == "" and fstype != "swap"

- name: Create swap on LV if it is swap
  command: mkswap /dev/{{ mount.value.vg_name }}/{{ mount.value.lv_name }}
  when: fs_type.stdout == "" and fstype == "swap"

- name: Check if mount point exists if it is not swap
  file:
    path: "{{ mount.key }}"
    state: directory
  when: fstype != "swap"

- name: Add mount point to fstab if it is not swap
  mount:
    path: "{{ mount.key }}"
    src: /dev/{{ mount.value.vg_name }}/{{ mount.value.lv_name }}
    fstype: "{{ fstype }}"
    state: mounted
  when: fstype != "swap"


- name: Add swap to fstab if it is swap
  mount:
    path: none
    src: /dev/{{ mount.value.vg_name }}/{{ mount.value.lv_name }}
    fstype: swap
    state: present
  when: fstype == "swap"

- name: Check if swap is already on
  command: swapon --show=NAME --noheadings
  register: swap_check
  ignore_errors: yes

- name: Get the mapper name of the swap
  command: realpath /dev/{{ mount.value.vg_name }}/{{ mount.value.lv_name }}
  register: mapper_name
  changed_when: false

- name: Enable swap if it is swap
  command: swapon /dev/{{ mount.value.vg_name }}/{{ mount.value.lv_name }}
  when: 
    - fstype == "swap"
    - mapper_name.stdout not in swap_check.stdout_lines